swagger: "2.0"
info:
  description: "This is a sample server express server that delivers weather data for a city"
  version: "1.0.0"
  title: "Dummy Weather Service"
  contact:
    email: "oshiro.hugo@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:9001"
basePath: "/"
tags:
- name: "weather"
  description: "Weather information by city"
schemes:
- "http"
paths:
  /weather/{cityId}:
    get:
      tags:
      - "weather"
      summary: "Get weather data by city zipcode or name"
      description: "Get weather data by city zipcode or name"
      operationId: "getWeatherById"
      produces:
      - "application/json"
      parameters:
      - name: "cityId"
        in: "path"
        description: "City id"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/WeatherData"
        500:
          description: "Internal server error"
definitions:
  WeatherData:
    type: "object"
    properties:
      cod:
        type: "string"
        example: "200"
      message:
        type: "number"
        format: "float"
        example: 0.003
      cnt:
        type: "integer"
        format: "int64"
        example: 39
      list:
        type: "array"
        items:
          $ref: '#/definitions/ListData'
  ListData:
    type: "object"
    properties:
      dt:
        type: "integer"
        format: "int64"
        example: 1523156400
      main:
        $ref: '#/definitions/Main'
      weather:
        $ref: '#/definitions/Weather'
      clouds:
        type: "object"
      wind:
        type: "object"
      rain:
        type: "object"
      sys:
        type: "object"
      dt_txt:
        type: "string"
        example: "2018-04-08 03:00:00"
  Main:
    type: "object"
    properties:
      temp:
        type: "number"
        format: "float"
        example: 4.93
      temp_min:
        type: "number"
        format: "float"
        example: 3.62
      temp_max:
        type: "number"
        format: "float"
        example: 4.93
      pressure:
        type: "number"
        format: "float"
        example: 1022.39
      sea_level:
        type: "number"
        format: "float"
        example: 1026.02
      grnd_level:
        type: "number"
        format: "float"
        example: 1022.39
      humidity:
        type: "number"
        format: "float"
        example: 72
      temp_kf:
        type: "number"
        format: "float"
        example: 1.31
  Weather:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        example: 804
      main:
        type: "string"
        example: "Clouds"
      description:
        type: "string"
        example: "overcast clouds"
      icon:
        type: "string"
        example: "04n"

